name = "GRAD Civs"
prefix = "grad_civs"
author = "Gruppe Adler"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3

files = [
    "adlerkopp_32.paa",
    "logo_64.paa",
    "logo_64_w.paa",
    "logo_1024_w.paa",
    "mod.cpp",
    "README.md"
]
include = [
    "./include"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip grad_civs-{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
